name: 'RRBUGproof2-BugBountySite'
description: 'Detect exposed API Keys.'
inputs:
  slack_hook:
    description: "Slack webhook to send alert to"
    required: false
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.slack_hook }}
