on:
  [issues]
jobs:
  detect_tests:
    runs-on: ubuntu-latest
    name: A workflow to test the work of DataSecure
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: CodeAnalysis
      uses: rrbugproof/GitSecure2.0@main
      with:
        slack_hook: ${{ secrets.slack_webhook }}
